name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust branch name if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Latest version

      - name: Setup Node.js
        uses: actions/setup-node@v4  # Latest version
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install  # Modify as per your build setup (if using npm)

      - name: Build site
        run: npm run build  # Modify as per your build setup (if using npm)

      - name: Ensure .well-known directory exists
        run: mkdir -p .well-known  # Ensure the .well-known directory exists

      - name: Create .nojekyll file
        run: echo '' > .well-known/.nojekyll  # Create a .nojekyll file inside .well-known

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Publish from the root directory